define({
	"AccessDenied": "Access denied",
	"Account": "Account",
	"ActivityFeed": "Activity feed",
	"Add": "Add",
	"Address": "Address",
	"AddressLookup": "Looking up address...",
	"AddressLookupSuccess": "Your address was found successfully.",
	"AddressLookupFail": "This address could not be found. You can still use it but you'll need to manually enter latitude and longitude if you'd like Hobson to calculate sunrise/sunset times.",
	"AddTask": "Create New Task",
  "baromInHg": "Barometric Pressure",
  "baromInHgUnits": "inches of Hg",
	"BetaPluginSettingUpdated": "Beta plugin setting updated.",
	"BetaPluginSettingFailed": "Failed to update beta plugin setting.",
	"Close": "Close",
	"TaskConditionActionPrompt": "Based on your available plugins/devices, the following are available:",
	"Dashboard": "Dashboard",
	"Debug": "Debug",
	"Devices": "Devices",
	"DeviceListRetrieveError": "Error retreiving device list.",
	"DeviceSelected": "device selected.",
	"DevicesSelected": "devices selected.",
	"DeviceConfigUpdateFailure": "Failed to update device configuration. See the log for details.",
	"DeviceConfigUpdateSuccess": "Successfully updated device configuration.",
	"DeviceMissingVariable": "This device does not have the expected information.",
  "dewPtF": "Dew Point",
  "dewPtFUnits": "degrees fahrenheit",
	"ecw": "Energy Consumption (watts)",
	"Email": "E-mail",
	"EnableDeviceStatistics": "Collect statistics for this device?",
	"Energy": "Energy",
	"EnterMailHost": "Enter the host name of IP address of your mail server",
	"EnterMailPassword": "Enter the password used to login to the mail server. Keep empty to leave unchanged.",
	"EnterMailReply": "Enter the reply address for sent e-mails",
	"EnterMailUser": "Enter the user name used to login to the mail server",
	"Error": "Error",
	"ErrorOccurred": "An error occurred. See the log for details.",
	"Friday": "Friday",
	"General": "General",
	"Gmail": "Gmail",
	"HomeInsight": "Home Insight",
	"Hubs": "Hubs",
	"HubName": "Hub name",
	"HubNamePrompt": "Enter a unique name for the Hub you are adding.",
	"HubSettings": "Hub Settings",
	"HubShuttingDown": "The Hub is shutting down.",
	"HubShutdownError": "An error occurred shutting down the Hub. See the log for details.",
	"IncludeBetaPlugins": "Show beta plugins",
	"Info": "Info",
	"inRh": "Indoor Humidity",
	"inRhUnits": "percent",
	"Insight": "Insight",
	"Install": "Install",
	"inTempF": "Indoor Temperature",
	"inTempFUnits": "degrees fahrenheit",
  "inTempC": "Indoor Temperature",
  "inTempCUnits": "degrees celsius",
	"IsRequiredField": "is a required field",
	"Latitude": "Latitude",
	"Log": "Log",
	"LogLevel": "Log level",
	"Login": "Login",
	"LogConfigurationSaved": "Log configuration saved.",
	"LogConfigurationSaveError": "Log configuration was not saved. See the log file for details.",
	"LogRetrievalError": "An error occurred retrieving the log file.",
	"Longitude": "Longitude",
	"lxLux": "Illuminance (lux)",
	"Monday": "Monday",
	"MustBeAValidDate": "must be a valid date",
	"MustBeAValidNumber": "must be a valid number",
	"MustBeAValidString": "must be a valid string",
	"MustBeAValidTime": "must be a valid time",
	"Name": "Name",
	"NextRun": "Next run",
	"NoDevicesAvailable": "There are no devices available that support this function.",
	"NoDevicesPublished": "There are no devices to display. You should <a href=\"#settings/plugins?filter=available\">install plugins</a> to create some.",
	"NoDevicesSelectedSingle": "No device is selected. Choose one from the list below.",
	"NoDevicesSelectedMultiple": "No devices are selected. Choose some from the list below.",
	"NoDevicesWereSelected": "No device(s) were selected.",
	"NoHubs": "No Hubs have been added.",
	"NoLatLong": "<a href=\"#settings/general\">Click here</a> to set your address.",
	"None": "None",
	"NoPluginsInstalled": "There are no plugins installed. Click the 'Available' link above to browse and install some.",
	"NoStatisticsEnabled": "Statistics are not enabled for this device.",
	"NoStatisticsCollected": "Device statistics are enabled but none have been received yet.",
	"NotScheduled": "Not scheduled today",
	"NoTasksCreated": "No tasks have been created.",
	"on": "On/Off",
	"Other": "Other",
	"outRh": "Outdoor Humidity",
	"outRhUnits": "percent",
	"outTempF": "Outdoor Temperature",
	"outTempFUnits": "degrees fahrenheit",
  "outTempC": "Outdoor Temperature",
  "outTempCUnits": "degrees celsius",
	"Password": "Password",
	"Plugins": "Plugins",
	"PluginConfigurationSaved": "The plugin configuration has been saved.",
	"PluginConfigurationNotSaved": "The plugin configuration could not be saved. Check the log for details.",
	"PluginConfigurationError": "Error retrieving plugin configuration",
	"PluginError": "Plugin startup error",
	"PluginInstallFailed": "The plugin failed to install. Please see the log for details.",
	"PluginInstallStarted": "The plugin is installing and will show up momentarily in your installed list.",
	"PluginUpdateAvailable": "An update for this plugin is available.",
	"PluginUpdateCheckError": "An error occurred checking for updates. See the log for details.",
	"Profile": "Profile",
	"RequiresConfiguration": "requires configuration.",
	"Saturday": "Saturday",
	"Save": "Save",
	"SelectDevices": "Select the device(s) below...",
	"SenderAddress": "Sender address",
	"SendTestMessage": "Send test message",
	"ServerCommError": "There was an error communicating with the server. Please try again momentarily.",
	"ServerHostname": "Server hostname",
	"ServerType": "Server type",
	"SessionExpired": "Your session has expired.",
	"Settings": "Settings",
	"ShowLatLong": "Show latitude/longitude",
	"State": "State",
	"Statistics": "Statistics",
	"Sunday": "Sunday",
	"targetTempF": "Target Temperature",
	"targetTempFUnits": "degrees fahrenheit",
	"Tasks": "Tasks",
	"TaskAdd": "Add Task",
	"TaskCreated": "The task was successfully created.",
	"TaskDeleteFail": "The task could not be deleted. See the log for details.",
	"TaskDeleteSuccess": "The task was successfully deleted.",
	"TaskIfHelpText": "You must add at least one condition that will cause the task to execute.",
	"TaskThenHelpText": "You must add at least one action that will execute when the task is run.",
	"TestMessageSuccessful": "Test message was sent successfully.",
	"TestMessageFailure": "An error occurred sending the test message.",
	"Thursday": "Thursday",
	"Trace": "Trace",
	"Tuesday": "Tuesday",
	"Update": "Update",
	"Username": "Username",
	"UserNameOrPasswordErrorMsg": "Username or password is incorrect.",
	"UseSecureConnection": "Use secure connection (SSL/TLS)",
	"Warn": "Warn",
	"Wednesday": "Wednesday",
	"windDirDeg": "Wind Direction",
	"windDirDegUnits": "degrees",
	"windSpdMph": "Wind Speed",
	"windSpdMphUnits": "miles per hour",
});
