define({
  "AccessDenied": "Access denied",
  "Account": "Account",
  "ActivityFeed": "Activity feed",
  "ActivityLogError": "Error retrieving activities. See the log for details.",
  "Add": "Add",
  "after": "after",
  "Activated": "Activated",
  "Address": "Address",
  "AddressLookup": "Looking up address...",
  "AddressLookupSuccess": "Your address was found successfully.",
  "AddressLookupFail": "This address could not be found. You can still use it but you'll need to manually enter latitude and longitude if you'd like Hobson to calculate sunrise/sunset times.",
  "AddTask": "Create New Task",
  "Advanced": "Advanced",
  "AreYouSureYouWantToDelete": "Are you sure you want to delete",
  "AreYouSureYouWantToManuallyExecute": "Are you sure you want to manually execute",
  "AtSunrise": "at sunrise",
  "AtSunset": "at sunset",
  "baromInHg": "Barometric Pressure",
  "baromInHgUnits": "inches of Hg",
  "Beacon": "Beacon",
  "BeaconMajor": "Beacon Major Number",
  "BeaconMinor": "Beacon Minor Number",
  "before": "before",
  "BetaPluginSettingUpdated": "Beta plugin setting updated.",
  "BetaPluginSettingFailed": "Failed to update beta plugin setting.",
  "Cameras": "Cameras",
  "Cancel": "Cancel",
  "Close": "Close",
  "color": "Color",
  "Cool": "Cool",
  "Create": "Create",
  "Created": "Created",
  "FieldName": "Field name",
  "FollowingErrorsOccurred": "The following errors occurred:",
  "TaskConditionActionPrompt": "Based on your available plugins and devices, the following options are available:",
  "Dashboard": "Dashboard",
  "DataStreamCreated": "The data stream was successfully created.",
  "DataStreamCreationFailed": "An error occurred creating the data stream.",
  "DataStreamCreationUnsupported": "Your Hub does not support the creation of data streams. Do you have the proper plugins installed?",
  "DataStreamDeleted": "Data stream has been successfully deleted.",
  "DataStreamHelpText": "You must add at least one field to the data stream.",
  "Debug": "Debug",
  "Description": "Description",
  "DeviceId": "Device ID",
  "Devices": "Devices",
  "DeviceAdded": "The device has been successfully added.",
  "DeviceListRetrieveError": "Error retrieving device list.",
  "DeviceSelected": "device selected",
  "DevicesSelected": "devices selected",
  "DeviceConfigUpdateFailure": "Failed to update device configuration. See the log for details.",
  "DeviceConfigUpdateSuccess": "Successfully updated device configuration.",
  "DeviceMissingVariable": "This device does not have the expected information.",
  "DeviceNotCheckedIn": "This device has not been in contact recently and may not be available.",
  "dewPtF": "Dew Point",
  "dewPtFUnits": "degrees fahrenheit",
  "ecw": "Energy Consumption (watts)",
  "EditTask": "Edit Task",
  "Email": "E-mail",
  "EnableDeviceStatistics": "Collect statistics for this device?",
  "EndDate": "End date",
  "EndDateDescription": "The date the task will stop repeating",
  "Energy": "Energy",
  "EnterDeviceId": "Enter the device's unique ID",
  "EnterLocationName": "Enter a friendly name for the location",
  "EnterMailHost": "Enter the host name of IP address of your mail server",
  "EnterMailPassword": "Enter the password used to login to the mail server. Keep empty to leave unchanged.",
  "EnterMailReply": "Enter the reply address for sent e-mails",
  "EnterMailUser": "Enter the user name used to login to the mail server",
  "EnterPersonName": "Enter a friendly name for the person",
  "Error": "Error",
  "ErrorOccurred": "An error occurred. See the log for details.",
  "Fields": "Fields",
  "Friday": "Friday",
  "General": "General",
  "GlobalVariableError": "Error retrieving global variables. See the log for details.",
  "Gmail": "Gmail",
  "HomeInsight": "Home Insight",
  "Hubs": "Hubs",
  "HubName": "Hub name",
  "HubNamePrompt": "Enter a unique name for the Hub you are adding.",
  "HubSettings": "Hub Settings",
  "HubShuttingDown": "The Hub is shutting down.",
  "HubShutdownError": "An error occurred shutting down the Hub. See the log for details.",
  "imageStatusUrl": "Image URL",
  "IncludeBetaPlugins": "Show beta plugins",
  "Info": "Info",
  "inRh": "Indoor Humidity",
  "inRhUnits": "percent",
  "Insight": "Insight",
  "Install": "Install",
  "inTempF": "Indoor Temperature",
  "inTempFUnits": "degrees fahrenheit",
  "inTempC": "Indoor Temperature",
  "inTempCUnits": "degrees celsius",
  "IsRequiredField": "is a required field",
  "IsExactly": "is exactly",
  "LastCheckIn": "Last check-in",
  "Latitude": "Latitude",
  "level": "Level",
  "LightsAndSwitches": "Lights & Switches",
  "Loading": "Loading",
  "LoadingLocations": "Loading locations...",
  "LoadingPeople": "Loading people...",
  "LocationCreated": "The location has been created.",
  "LocationCreatedFailed": "Unable to create location. See the log file for details.",
  "LocationDeleted": "The location has been deleted.",
  "LocationDeletedError": "An error occurred deleting the location. See the log file for details.",
  "LocationRetrieveError": "An error occurred retrieving locations. See the log file for details.",
  "Locations": "Locations",
  "LocationsSummary": "This is a list of locations you want to track people arriving at or departing from. A location can be either map-based or beacon-based.",
  "Log": "Log",
  "LogLevel": "Log level",
  "Login": "Login",
  "Logout": "Logout",
  "LogConfigurationSaved": "Log configuration saved.",
  "LogConfigurationSaveError": "Log configuration was not saved. See the log file for details.",
  "LogRetrievalError": "An error occurred retrieving the log file.",
  "Longitude": "Longitude",
  "lxLux": "Illuminance (lux)",
  "Map": "Map",
  "Menu": "Menu",
  "Monday": "Monday",
  "mins": "mins.",
  "Miscellaneous": "Miscellaneous",
  "MustBeAValidDate": "must be a valid date",
  "MustBeAValidNumber": "must be a valid number",
  "MustBeAValidString": "must be a valid string",
  "MustBeAValidTime": "must be a valid time",
  "Name": "Name",
  "NeedsName": "You must provide a name.",
  "NeedOneAction": "There must be at least one action defined.",
  "NeedOneCondition": "There must be at least one condition defined.",
  "NeedOneVariable": "There must be at least one variable defined.",
  "Neutral": "Neutral",
  "NextRun": "Next run",
  "NewDataStream": "New Data Stream",
  "NewDevice": "New Device",
  "NewLocation": "New Location",
  "NewPerson": "New Person",
  "NewTask": "New Task",
  "NoAdditionalItemsAppropriate": "No additional items are appropriate here.",
  "NoDataAvailable": "No data is available for the requested time period.",
  "NoDataStreamsCreated": "No data streams have been created.",
  "NoDevicesAvailable": "There are no devices available that support this function.",
  "NoDevicesPublished": "There are no devices to display. You should <a href=\"#settings/plugins?filter=available\">install plugins</a> to create some.",
  "NoDevicesSelectedSingle": "none selected",
  "NoDevicesSelectedMultiple": "none selected",
  "NoDevicesWereSelected": "No device(s) were selected.",
  "NoHubs": "No Hubs have been added.",
  "NoLatLong": "<a href=\"#settings/general\">Click here</a> to set your address.",
  "NoLocations": "No locations have been created.",
  "NoPeople": "No people have been created.",
  "None": "None",
  "NoPluginsAvailable": "There are no additional plugins available.",
  "NoPluginsInstalled": "There are no plugins installed. Click the 'Available' link above to browse and install some.",
  "NoStatisticsEnabled": "Statistics are not enabled for this device.",
  "NoStatisticsCollected": "Device statistics are enabled but none have been received yet.",
  "NotScheduled": "Not scheduled today",
  "NoTasksCreated": "No tasks have been created.",
  "NoVariablesAvailable": "There are no variables for the selected item.",
  "on": "On/Off",
  "OnlyOnTheseDays": "Only on these days",
  "Other": "Other",
  "outRh": "Outdoor Humidity",
  "outRhUnits": "percent",
  "outTempF": "Outdoor Temperature",
  "outTempFUnits": "degrees fahrenheit",
  "outTempC": "Outdoor Temperature",
  "outTempCUnits": "degrees celsius",
  "Password": "Password",
  "People": "People",
  "PeopleSummary": "This is a list of people with devices that can provide presence information (e.g. smart phones). Each person will need the Hobson app installed and configured on their device for presence to work.",
  "PersonCreated": "The person has been created.",
  "PersonCreatedError": "An error occurred creating the person. Check the log for details.",
  "PersonDeleted": "The person has been deleted.",
  "PersonDeletedError": "An error occurred deleting the person. Check the log for details.",
  "PersonRetrieveError": "An error occurred retrieving people. Check the log for details.",
  "Plugins": "Plugins",
  "PluginConfigurationSaved": "The plugin configuration has been saved.",
  "PluginConfigurationNotSaved": "The plugin configuration could not be saved. Check the log for details.",
  "PluginConfigurationError": "Error retrieving plugin configuration",
  "PluginError": "Plugin startup error",
  "PluginInstallFailed": "The plugin failed to install. Please see the log for details.",
  "PluginInstallStarted": "The plugin is installing and will show up momentarily in your installed list.",
  "PluginUpdateAvailable": "An update for this plugin is available.",
  "PluginUpdateCheckError": "An error occurred checking for updates. See the log for details.",
  "Presence": "Presence",
  "PressToArm": "Press to arm",
  "PressToDisarm": "Press to disarm",
  "Profile": "Profile",
  "Radius": "Radius",
  "Required": "Required",
  "RequiresConfiguration": "requires configuration.",
  "Saturday": "Saturday",
  "Save": "Save",
  "SelectDevices": "Select the device(s) below...",
  "SenderAddress": "Sender address",
  "SendTestMessage": "Send test message",
  "Sensors": "Sensors",
  "ServerCommError": "There was an error communicating with the server. Please try again momentarily.",
  "ServerHostname": "Server hostname",
  "ServerType": "Server type",
  "SessionExpired": "Your session has expired.",
  "Settings": "Settings",
  "ShowLatLong": "Manually set latitude/longitude",
  "ShutdownHub": "Shutdown Hub",
  "State": "State",
  "Statistics": "Statistics",
  "Sunday": "Sunday",
  "SunriseSunsetDisabled": "No address or lat/long set - sunrise/sunset is disabled.",
  "targetTempF": "Target Temperature",
  "targetTempFUnits": "degrees fahrenheit",
  "TaskExactTOD": "The exact time of day the task will occur",
  "TaskRelativeTOD": "The time of day that task will occur relative to sunrise/sunset",
  "Tasks": "Tasks",
  "TaskAdd": "Add Task",
  "TaskCreated": "Task created.",
  "TaskDeleteFail": "The task could not be deleted. See the log for details.",
  "TaskDeleteSuccess": "The task was successfully deleted.",
  "TaskExecuteSuccess": "The task was successfully executed.",
  "TaskExecuteFailure": "The task failed to execute. Please see the log file for details.",
  "TaskIfHelpText": "You must add at least one condition that will cause the task to execute.",
  "TaskThenHelpText": "You must add at least one action that will execute when the task is run.",
  "TestMessageSuccessful": "Test message was sent successfully.",
  "TestMessageFailure": "An error occurred sending the test message.",
  "ThisIsRequiredField": "This is a required field.",
  "Thursday": "Thursday",
  "Trace": "Trace",
  "Type": "Type",
  "Tuesday": "Tuesday",
  "Update": "Update",
  "Username": "Username",
  "UserNameOrPasswordErrorMsg": "Username or password is incorrect.",
  "UseSecureConnection": "Use secure connection (SSL/TLS)",
  "Variables": "Variables",
  "WaitingForCameraImage": "Waiting for camera image...",
  "Warm": "Warm",
  "Warn": "Warn",
  "Wednesday": "Wednesday",
  "windDirDeg": "Wind Direction",
  "windDirDegUnits": "degrees",
  "windSpdMph": "Wind Speed",
  "windSpdMphUnits": "miles per hour",
});
