define({
	"AccessDenied": "Access denied",
	"Account": "Account",
	"ActivityFeed": "Activity feed",
	"Add": "Add",
	"Address": "Address",
	"AddressLookup": "Looking up address...",
	"AddressLookupSuccess": "Your address was found successfully.",
	"AddressLookupFail": "This address could not be found. You can still use it but you'll need to manually enter latitude and longitude if you'd like Hobson to calculate sunrise/sunset times.",
	"AddTask": "Create New Task",
	"Dashboard": "Dashboard",
	"Debug": "Debug",
	"Devices": "Devices",
	"DeviceSelected": "device selected.",
	"DevicesSelected": "devices selected.",
	"DeviceConfigUpdateFailure": "Failed to update device configuration. See the log for details.",
	"DeviceConfigUpdateSuccess": "Successfully updated device configuration.",
	"Email": "E-mail",
	"EnableDeviceStatistics": "Collect statistics for this device?",
	"Energy": "Energy",
	"EnterMailHost": "Enter the host name of IP address of your mail server",
	"EnterMailPassword": "Enter the password used to login to the mail server. Keep empty to leave unchanged.",
	"EnterMailReply": "Enter the reply address for sent e-mails",
	"EnterMailUser": "Enter the user name used to login to the mail server",
	"Error": "Error",
	"ErrorOccurred": "An error occurred. See the log for details.",
	"Friday": "Friday",
	"General": "General",
	"Gmail": "Gmail",
	"HomeInsight": "Home Insight",
	"Hubs": "Hubs",
	"HubName": "Hub name",
	"HubNamePrompt": "Enter a unique name for the Hub you are adding.",
	"HubSettings": "Hub Settings",
	"Info": "Info",
	"Insight": "Insight",
	"Latitude": "Latitude",
	"Log": "Log",
	"LogLevel": "Log level",
	"Login": "Login",
	"Longitude": "Longitude",
	"Monday": "Monday",
	"Name": "Name",
	"NoActionsNotice": "Click the <i class=\"fa fa-plus\"></i> below to add one.",
	"NoConditionsNotice": "Click the <i class=\"fa fa-plus\"></i> below to set one.",
	"NoDevicesSelected": "No devices are selected. Choose from the list below.",
	"NoHubs": "No Hubs have been added.",
	"None": "None",
	"NoStatisticsEnabled": "Statistics are not enabled for this device.",
	"NoStatisticsCollected": "Device statistics are enabled but none have been received yet.",
	"Other": "Other",
	"Password": "Password",
	"Plugins": "Plugins",
	"PluginConfigurationSaved": "The plugin configuration has been saved.",
	"PluginConfigurationNotSaved": "The plugin configuration could not be saved. Check the log for details.",
	"PluginError": "Plugin startup error",
	"Profile": "Profile",
	"RequiresConfiguration": "requires configuration.",
	"Saturday": "Saturday",
	"Save": "Save",
	"SelectDevices": "Select the device(s) below...",
	"SenderAddress": "Sender address",
	"SendTestMessage": "Send test message",
	"ServerCommError": "There was an error communicating with the server. Please try again momentarily.",
	"ServerHostname": "Server hostname",
	"ServerType": "Server type",
	"SessionExpired": "Your session has expired.",
	"Settings": "Settings",
	"ShowLatLong": "Show latitude/longitude",
	"State": "State",
	"Statistics": "Statistics",
	"Sunday": "Sunday",
	"targetTempF": "Target Temperature (F)",
	"Tasks": "Tasks",
	"TaskAdd": "Add Task",
	"TaskIfHelpText": "This is the condition that will trigger the task.",
	"TaskThenHelpText": "These are the actions that will occur when the task is triggered.",
	"tempF": "Temperature (F)",
	"TestMessageSuccessful": "Test message was sent successfully.",
	"TestMessageFailure": "An error occurred sending the test message.",
	"Thursday": "Thursday",
	"Trace": "Trace",
	"Tuesday": "Tuesday",
	"Username": "Username",
	"UserNameOrPasswordErrorMsg": "Username or password is incorrect.",
	"UseSecureConnection": "Use secure connection (SSL/TLS)",
	"Warn": "Warn",
	"Wednesday": "Wednesday"
});